<a href="https://colab.research.google.com/github/Chinu2522/2101206032/blob/main/python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
import numpy as np
list1=[0,1,2,3,4]
list1=list1+2

TypeError: ignored

In [3]:
import numpy as np
list1=[0,1,2,3,4]
a=np.array(list1)
print(a)
a=a+2
print(a)

[0 1 2 3 4]
[2 3 4 5 6]


In [5]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

print(arr*5)

print(arr+10)

[[1 2 3]
 [4 5 6]]
[[ 5 10 15]
 [20 25 30]]
[[11 12 13]
 [14 15 16]]


In [6]:
import numpy as np
list2=[[0,1,2],[3,4,5],[6,7,8]]
a3=np.array(list2,dtype='str')
print(a3)

[['0' '1' '2']
 ['3' '4' '5']
 ['6' '7' '8']]


In [7]:
import numpy as np
list2=[[0,1,2],[3,4,5],[6,7,8]]
a3=np.array(list2,dtype='float')
print(a3)
a3_s=a3.astype('int').astype('str')
print(a3_s)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[['0' '1' '2']
 ['3' '4' '5']
 ['6' '7' '8']]


In [8]:
arr_obj=np.array([1,'a'],dtype='object')
print(arr_obj)

[1 'a']


In [9]:
import numpy as np
list=[[0,1,2],[3,4,5],[6,7,8]]
arr=np.array(list,dtype='float')
print(arr)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [10]:
import numpy as np
list=[[0,1,2],[3,4,5],[6,7,8]]
a3=np.array(list,dtype='float')
print('shape:',a3.shape)
print('Datatype:',a3.dtype)
print('Size:',a3.size)
print('Num dimension:',a3.ndim)

shape: (3, 3)
Datatype: float64
Size: 9
Num dimension: 2
